### ISSUE TITLE
chapter9 RuntimeError: unexpected EOF. The file might be corrupted.

### ISSUE THREAD

**Issue by reallyisafool** [chenyuntc/pytorch-book#120]
您好，我试图使用您提供预训练好的模型以生成诗词。
但出现如下报错
```
Traceback (most recent call last):
  File "main.py", line 231, in <module>
    fire.Fire()
  File "/opt/anaconda/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/opt/anaconda/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/opt/anaconda/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "main.py", line 200, in gen
    state_dict = t.load(opt.model_path, map_location=map_location)
  File "/opt/anaconda/lib/python3.7/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/opt/anaconda/lib/python3.7/site-packages/torch/serialization.py", line 549, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF. The file might be corrupted.

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by chenjun2hao** [comment]
@reallyisafool 请问这个问题你解决了吗
