### ISSUE TITLE
chapter 7 第七章代码报错

### ISSUE THREAD

**Issue by GH1995** [chenyuntc/pytorch-book#127]
```
Traceback (most recent call last):
  File "main.py", line 194, in <module>
    fire.Fire()
  File "/home/hua_guan/anaconda3/envs/pch/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/hua_guan/anaconda3/envs/pch/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/hua_guan/anaconda3/envs/pch/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "main.py", line 150, in train
    tv.utils.save_image(fix_fake_imgs.data[:64], '%s/%s.png' % (opt.save_path, epoch), normalize=True,
UnboundLocalError: local variable 'fix_fake_imgs' referenced before assignment
```

`python`运行语句如下：
```
python main.py train --vis=False --data_path=/home/hua_guan/data
```

环境是`conda 4.6.4` `python 3.6.8` `Ubuntu 16.04`

**Comment by GH1995** [comment]
#67

**Comment by GH1995** [comment]
@chenyuntc 还是没有解决这个问题，可以贴一下具体的代码吗？

**Comment by zpeng1989** [comment]
我在报错那句前面加了
`fix_fake_imgs = netg(fix_noises)`
运行成功了
