### ISSUE TITLE
我在第六章我第七章都遇到同样的报错，一个是tqdm的报错，一个是Normalize的报错！

### ISSUE THREAD

**Issue by qxzhou1010** [chenyuntc/pytorch-book#141]
0it [00:00, ?it/s]Traceback (most recent call last):
  File "/home/xiaopang/Downloads/pytorch-book-master/chapter7-GAN生成动漫头像/main.py", line 195, in <module>
    train()
  File "/home/xiaopang/Downloads/pytorch-book-master/chapter7-GAN生成动漫头像/main.py", line 104, in train
    for ii, (img, _) in tqdm.tqdm(enumerate(dataloader)):
  File "/home/xiaopang/anaconda3/envs/pytorch/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1022, in __iter__
    for obj in iterable:
  File "/home/xiaopang/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/xiaopang/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/home/xiaopang/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/xiaopang/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/xiaopang/anaconda3/envs/pytorch/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 103, in __getitem__
    sample = self.transform(sample)
  File "/home/xiaopang/anaconda3/envs/pytorch/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/home/xiaopang/anaconda3/envs/pytorch/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 163, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
TypeError: normalize() takes 3 positional arguments but 4 were given

我用的PyTorch1.0,我调试了很久，都没能解决，代码都是用的作者本人的代码

**Comment by zpeng1989** [comment]
我也遇到了，后来发现是少写了一行，你可以看看；估计某行可能被注释掉了
