### ISSUE TITLE
第十章 KeyError: tensor(312, device='cuda:0')

### ISSUE THREAD

**Issue by wlybug** [chenyuntc/pytorch-book#143]
Traceback (most recent call last):
  File "main.py", line 125, in <module>
    fire.Fire()
  File "/data/wangly/.local/share/virtualenvs/python3-tN7JoeU3/lib/python3.5/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/data/wangly/.local/share/virtualenvs/python3-tN7JoeU3/lib/python3.5/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/data/wangly/.local/share/virtualenvs/python3-tN7JoeU3/lib/python3.5/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "main.py", line 113, in train
    raw_caption = ''.join([_data['ix2word'][ii] for ii in raw_caption])
  File "main.py", line 113, in <listcomp>
    raw_caption = ''.join([_data['ix2word'][ii] for ii in raw_caption])
KeyError: tensor(312, device='cuda:0')

**Comment by yhwhu** [comment]
我也是类似这种错误，希望能帮忙一下

**Comment by thinkpadt68** [comment]
一样一样，希望有人可以解答一下

**Comment by thinkpadt68** [comment]
@yhwhu @wlybug https://github.com/chenyuntc/pytorch-book/issues/93   前面有人把这问题解决了
