### ISSUE TITLE
第9章charnn运行报错ValueError: num_samples should be a positive integeral value, but got num_samples=0

### ISSUE THREAD

**Issue by Invokar** [chenyuntc/pytorch-book#150]
`
Traceback (most recent call last):
  File "main.py", line 234, in <module>
    fire.Fire()
  File "/home/zhangqilong/anaconda3/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/zhangqilong/anaconda3/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/zhangqilong/anaconda3/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "main.py", line 140, in train
    num_workers=1)
  File "/home/zhangqilong/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 802, in __init__
    sampler = RandomSampler(dataset)
  File "/home/zhangqilong/anaconda3/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 64, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integeral value, but got num_samples=0
`

**Comment by zishuYM** [comment]
把pickle_path改为'data/tang.npz'

**Comment by Invokar** [comment]
> 把pickle_path改为'data/tang.npz'

谢谢，我之前已经解决了~

**Comment by ilovekj** [comment]
您好,我遇到同样的，请问是什么问题

**Comment by Invokar** [comment]
> 您好,我遇到同样的，请问是什么问题

.npy文件没有下载好

**Comment by ilovekj** [comment]
谢谢，我解决了

**Comment by zoulu995** [comment]
我在第六章遇到这个问题，请你们具体是如何解决的？感谢！

**Comment by zishuYM** [comment]
把pickle_path改为'data/tang.npz'
或者是npy文件没下载好。




------------------ 原始邮件 ------------------
发件人: "Tom Zou"<notifications@github.com>;
发送时间: 2019年7月18日(星期四) 上午10:30
收件人: "chenyuntc/pytorch-book"<pytorch-book@noreply.github.com>;
抄送: "严明"<865509329@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [chenyuntc/pytorch-book] 第9章charnn运行报错ValueError: num_samples should be a positive integeral value, but got num_samples=0 (#150)




我在第六章遇到这个问题，请你们具体是如何解决的？感谢！

**Comment by zoulu995** [comment]
> 把pickle_path改为'data/tang.npz' 或者是npy文件没下载好。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Tom Zou"<notifications@github.com>; 发送时间: 2019年7月18日(星期四) 上午10:30 收件人: "chenyuntc/pytorch-book"<pytorch-book@noreply.github.com>; 抄送: "严明"<865509329@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [chenyuntc/pytorch-book] 第9章charnn运行报错ValueError: num_samples should be a positive integeral value, but got num_samples=0 (#150) 我在第六章遇到这个问题，请你们具体是如何解决的？感谢！ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

感谢，问题解决啦！！！！
