### ISSUE TITLE
AttributeError: module 'torch.utils' has no attribute 'data'

### ISSUE THREAD

**Issue by XHG78999** [chenyuntc/pytorch-book#208]
当我执行这里的诗歌生成代码时，出现了一个问题：
```
Traceback (most recent call last):
  File "C:\Users\朋友的朋\Desktop\诗歌生成\main.py", line 259, in <module>
    train()
  File "C:\Users\朋友的朋\Desktop\诗歌生成\main.py", line 137, in train
    dataloader = t.utils.data.DataLoader(data,
AttributeError: module 'torch.utils' has no attribute 'data'
```
不知道什么意思，求指教。

**Comment by GarveyZ** [comment]
先看一下torch包中存不存在data这个方法。
如果不存在，重新安装torch
如果存在，看一下是不是torch没有声明。。。
