### ISSUE TITLE
第六章 Resnet out of memory错误

### ISSUE THREAD

**Issue by arisliang** [chenyuntc/pytorch-book#37]
根据#23 的建议,换去ResNet, 出现out of memory的错误. 我的显卡是6GB.

> THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1518244421288/work/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "/home/ly/src/pytorch-examples/chenyun-pytorch/ch6/main.py", line 182, in <module>
    fire.Fire()
  File "/home/ly/anaconda3/envs/learning/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/ly/anaconda3/envs/learning/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/ly/anaconda3/envs/learning/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/home/ly/src/pytorch-examples/chenyun-pytorch/ch6/main.py", line 85, in train
    score = model(input)
  File "/home/ly/anaconda3/envs/learning/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ly/src/pytorch-examples/chenyun-pytorch/ch6/models/ResNet34.py", line 71, in forward
    x = self.layer2(x)
  File "/home/ly/anaconda3/envs/learning/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ly/anaconda3/envs/learning/lib/python3.6/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/ly/anaconda3/envs/learning/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ly/src/pytorch-examples/chenyun-pytorch/ch6/models/ResNet34.py", line 24, in forward
    return F.relu(out)
  File "/home/ly/anaconda3/envs/learning/lib/python3.6/site-packages/torch/nn/functional.py", line 583, in relu
    return threshold(input, 0, 0, inplace)
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1518244421288/work/torch/lib/THC/generic/THCStorage.cu:58

**Comment by chenyuntc** [comment]
把batch size 换小 一点试试，比如--batch-size=4

**Comment by arisliang** [comment]
batch size换去4就可以了, GPU 内存占用2gb多.
