### ISSUE TITLE
第十章 图像描述  在更新pytorch以后出现问题

### ISSUE THREAD

**Issue by ROCKBOOM** [chenyuntc/pytorch-book#41]
### 运行命令：python feature_extract.py 出现以下错误
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "F:\Anaconda\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "F:\Anaconda\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "F:\Anaconda\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "F:\Anaconda\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "F:\Anaconda\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "F:\Anaconda\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "F:\Anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "G:\图像描述(Image Caption)\feature_extract.py", line 68, in <module>
    for ii,(imgs, indexs)  in tqdm.tqdm(enumerate(dataloader)):
  File "F:\Anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 417, in __iter__
    return DataLoaderIter(self)
  File "F:\Anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 234, in __init__
    w.start()
  File "F:\Anaconda\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "F:\Anaconda\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "F:\Anaconda\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "F:\Anaconda\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "F:\Anaconda\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "F:\Anaconda\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "feature_extract.py", line 68, in <module>
    for ii,(imgs, indexs)  in tqdm.tqdm(enumerate(dataloader)):
  File "F:\Anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 417, in __iter__
    return DataLoaderIter(self)
  File "F:\Anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 234, in __init__
    w.start()
  File "F:\Anaconda\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "F:\Anaconda\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "F:\Anaconda\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "F:\Anaconda\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "F:\Anaconda\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
```
### 问题描述：
因为我的电脑没有Nvidia的显卡，所以之前运行**python feature_extract.py**时出现错误：**Torch not compiled with CUDA enabled**，所以就安装了带有CUDA版本的pytorch，结果导入错误，于是就把所有的pytorch框架都删了，装上了一个最新的（其实版本好像还是0.3.1），重新运行了命令：**python feature_extract.py**，就报了以上的错误。至于报错里提到的：**if __name__ == '__main__':** 问题，我也在**feature_extract.py**文件里加上了这句判断，可是依然报这个错。google了**BrokenPipeError: [Errno 32] Broken pipe**的相关问题，基本都是socket的报错，帮助不大，特地跑来发问。深度学习的小白，坐等大神解答疑惑。

**Comment by jizongFox** [comment]
I have met the same problem.
Here, you can remove all your code under:
if __name__=="__main__":
And your algorithm might work properly.

**Comment by jizongFox** [comment]
![image](https://user-images.githubusercontent.com/24821325/39371505-e5b37ef4-4a0f-11e8-828c-e4f894a4ee35.png)

**Comment by ROCKBOOM** [comment]
@jizongFox thank you so much,The problem has been solved. Puzzled me for a long time.
