### ISSUE TITLE
第六章训练部分 Runtime Error

### ISSUE THREAD

**Issue by lixiny** [chenyuntc/pytorch-book#49]
在第六章的猫狗训练过程中： 
File "main.py", line 123, in train
    if loss_meter.value()[0] > previous_loss:          
**RuntimeError: value cannot be converted to type float without overflow:** 10000000000000000159028911097599180468360808563945281389781327557747838772170381060813469985856815104.000000

**Comment by zchrissirhcz** [comment]
@chenyuntc @lixiny 我也遇到同样的错误。

我用的是python2.7.12，ubuntu16.04, 代码切换到v0.4分支运行的。代码没有修改过，直接运行的，完整输出内容如下：

```
➜  kk python main.py train --use-gpu=True --env=classifier
user config:
('num_workers', 4)
('max_epoch', 10)
('batch_size', 32)
('parse', <bound method DefaultConfig.parse of <config.DefaultConfig object at 0x7f9eef6bf550>>)
('test_data_root', './data/test1')
('result_file', 'result.csv')
('weight_decay', 0.0)
('load_model_path', None)
('use_gpu', True)
('print_freq', 20)
('debug_file', '/tmp/debug')
('lr', 0.001)
('env', 'classifier')
('train_data_root', './data/train/')
('model', 'ResNet34')
('lr_decay', 0.5)
/usr/local/lib/python2.7/dist-packages/torchvision/transforms/transforms.py:188: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
/usr/local/lib/python2.7/dist-packages/torchvision/transforms/transforms.py:563: UserWarning: The use of the transforms.RandomSizedCrop transform is deprecated, please use transforms.RandomResizedCrop instead.
  "please use transforms.RandomResizedCrop instead.")
0it [00:00, ?it/s]main.py:99: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  loss_meter.add(loss.data[0])
547it [02:15,  4.02it/s]
0it [00:00, ?it/s]main.py:138: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  val_input = Variable(input, volatile=True)
235it [00:21, 10.96it/s]
Traceback (most recent call last):
  File "main.py", line 169, in <module>
    fire.Fire()
  File "/usr/local/lib/python2.7/dist-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/local/lib/python2.7/dist-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/usr/local/lib/python2.7/dist-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "main.py", line 121, in train
    if loss_meter.value()[0] > previous_loss:          
RuntimeError: value cannot be converted to type float without overflow: 10000000000000000159028911097599180468360808563945281389781327557747838772170381060813469985856815104.000000
```

**Comment by zchrissirhcz** [comment]
@chenyuntc 从tensor中取值，新版pytorch要使用.item()，应该是这个原因。

```python
#if loss_meter.value()[0] > previous_loss:
if loss_meter.value()[0].item() > previous_loss:

#previous_loss = loss_meter.value()[0]
previous_loss = loss_meter.value()[0].item()
```
