### ISSUE TITLE
chapter9 我跑了藏头诗有个报错希望得到解决

### ISSUE THREAD

**Issue by zxdxjtu** [chenyuntc/pytorch-book#53]
Traceback (most recent call last):
  File "main.py", line 231, in <module>
    fire.Fire()
  File "/Users/zhangxindong/Desktop/experiment/pytorch-book/pytorch/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/Users/zhangxindong/Desktop/experiment/pytorch-book/pytorch/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/Users/zhangxindong/Desktop/experiment/pytorch-book/pytorch/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "main.py", line 224, in gen
    result = gen_poetry(model, start_words, ix2word, word2ix, prefix_words)
  File "main.py", line 105, in gen_acrostic
    w = ix2word[top_index]
KeyError: tensor(6522)

**Comment by majinshan** [comment]
w = ix2word[top_index.item()]

**Comment by chenyuntc** [comment]
Support for PyTorch 0.4 will come out in next version.
