### ISSUE TITLE
第六章 代码出现 NameError

### ISSUE THREAD

**Issue by suzhengpeng** [chenyuntc/pytorch-book#59]
A:\python\test>python main.py help

    usage : python file.py <function> [--args=value]
    <function> := train | test | help
    example:
            python main.py train --env='env0701' --lr=0.01
            python main.py test --dataset='path/to/dataset/root/'
            python main.py help
    avaiable args:
Traceback (most recent call last):
  File "main.py", line 169, in <module>
    import fire
  File "D:\Anaconda3\lib\site-packages\fire\core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "D:\Anaconda3\lib\site-packages\fire\core.py", line 366, in _Fire
    component, remaining_args)
  File "D:\Anaconda3\lib\site-packages\fire\core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "main.py", line 164, in help
    from inspect import getsource
NameError: name 'opt' is not defined

请问如何解决呢？

**Comment by wutomwu** [comment]
#coding:utf8 改为 #coding:utf-8

**Comment by chenyuntc** [comment]
@wutoutu 多谢.
