### ISSUE TITLE
Chapter 9: RuntimeError: torch.cuda.FloatTensor is not enabled.

### ISSUE THREAD

**Issue by fuermosi777** [chenyuntc/pytorch-book#63]
Hi. I got an error when following the tutorial and ran `python main.py train --ploy-every=150 --batch-size=128 --pickle-path='tang.npz' --lr=1e-3  --env='poetry3' --epoch=50`

It throws an error: `RuntimeError: torch.cuda.FloatTensor is not enabled.`

I tried both python 2.7.10 and python 3.6.5 but no luck.

Thanks!

**Comment by AhmedCheikhRouhou** [comment]
I just upgraded pytorch to 0.4.0 the same error was thrown. Maybe you need to downgrade the version of pytorch to 0.3.0 or something else.

**Comment by chenyuntc** [comment]
Could you give a more detail traceback？ I wanna know which line code raises the error.

**Comment by fuermosi777** [comment]
Here is the full log:
```
Traceback (most recent call last):
  File "main.py", line 231, in <module>
    fire.Fire()
  File "/Users/blurred/private/PyTorch-book/env/lib/python2.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/Users/blurred/private/PyTorch-book/env/lib/python2.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/Users/blurred/private/PyTorch-book/env/lib/python2.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "main.py", line 149, in train
    model.cuda()
  File "/Users/blurred/private/PyTorch-book/env/lib/python2.7/site-packages/torch/nn/modules/module.py", line 249, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/Users/blurred/private/PyTorch-book/env/lib/python2.7/site-packages/torch/nn/modules/module.py", line 176, in _apply
    module._apply(fn)
  File "/Users/blurred/private/PyTorch-book/env/lib/python2.7/site-packages/torch/nn/modules/module.py", line 182, in _apply
    param.data = fn(param.data)
  File "/Users/blurred/private/PyTorch-book/env/lib/python2.7/site-packages/torch/nn/modules/module.py", line 249, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: torch.cuda.FloatTensor is not enabled.

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by TJJTJJTJJ** [comment]
You maybe run only model.cuda() to try to know where is the error. or t.cuda.is_available() to check out your  cuda is good or bad?

**Comment by duguiming111** [comment]
model.load_state_dict(state_dict, strict=False)这样就可以了
